### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by bigdigital** [bigdigital/watchdrip#2]
My TODO list for watchdrip

- [x]  Add watch store(gallery)
- [x] Add the possibility to add a list of watches in Watchdrip+ to change from one to another easily (prop by 
Miguel on Patreon) 
- [x] Investigate ZEPPOS wathface structure
- [x] Implement in app local server for communications with ZEPPOS

**Comment by DOFfactory** [comment]
I would also suggest a build for Android 13. Currently WatchDrip+ does not run on Pixel 7 phone, not sure whether it is due to droping the 32bit builds and supporting exclusively 64bit builds. 

Also, nighttime lower LCD brightness settings are not respected, unfortunately waking up my significant other with full brightness.

Hope this feedback is helpful, keep up the good work!

**Comment by dircsem** [comment]
Is it possible to change the app data source from api to broadcast? This would include aaps compatibility for a source, instead of xdrip.
Can you share the code here? Bolus display isn't working at my watch I would like to take a look at it to see if I can help.

**Comment by bigdigital** [comment]
@dircsem  > Is it possible to change the app data source from api to broadcast? This would include aaps compatibility for a source, instead of xdrip.
> Can you share the code here? Bolus display isn't working at my watch I would like to take a look at it to see if I can help.
The project source code was updated. There is no bolus because this data is not transferring from xDrip itself. I made a pull request, but it is still not merged  https://github.com/NightscoutFoundation/xDrip/pull/2294
